//! Implementations of interrupts.
#![cfg(target_arch = "x86")]
#![allow(undefined_naked_function_abi)] // special calling convention anyway

use core::arch::naked_asm;

macro_rules! int_wrapper {
    ($func:block, $num:expr) => {
        paste::paste! {
            /// autogenerated interrupt wrapper
            #[naked]
            pub unsafe fn [< int $num >]() {
                unsafe {
                    naked_asm!(
                        "pushad",
                        "cld",
                        "call {}",
                        "popad",
                        "iret",
                        sym [< int $num _rust >]
                    )
                }
            }

            /// autogenerated interrupt body
            unsafe extern "C" fn [< int $num _rust >]() $func
        }
    };
}

int_wrapper!(
    {
        super::output::sdebugsln("Interrupt handler #0 ran");
    },
    0
);
