name: Format code
on: [push]

jobs:
  format-kernel:
    name: Format the kernel
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: msrd0/rust-toolchain@nightly
      - run: rustup component add rustfmt
      - run: |
          cd kernel
          ./format
      - name: Commit format
        run: |
          git config --global user.name 'Formatter'
          git config --global user.email 'formatter@noreply.git.verygay.fyi'
          git commit -am "Automated format" || true
          git push || true
      