#!/bin/bash

(
    set -e

    
    export KERNEL_DIR=$(readlink -e .)

    DIR="${BASH_SOURCE%/*}"
    if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

    . "$DIR/functions"

    # -f makes it so it won't error out if the file doesn't exist
    rm -f config.aphro.tmp
    envsubst < "config.aphro" > "config.aphro.tmp"

    # see above about -f
    rm -f targets.tmp
    envsubst < "targets" > "targets.tmp"

    export $(grep -Ev '^#' targets.tmp | xargs)

    export $(grep -Ev '^#' config.aphro.tmp | xargs)

    get_version

    if [[ "$CFG_VERSION" != "$VERSION" ]]; then
        echo -n "[WARN] Configuration version \"$CFG_VERSION\" is different then actual version \"$VERSION\""
        if [[ "$CONT_WITH_DIFFERENT_VERSION" != "true" ]]; then
            echo "; not continuing"
            exit 1
        fi
        echo
    fi

    cd ../kernel

    for target in $TARGETS; do
        real_target=${!target}
        cargo build --target "$real_target" --release -Zbuild-std --bin entrypoint_$target
        cp target/i686-unknown-none/release/entrypoint_$target kernel.flat

        if [[ "$CONFIG_BUILD_GRUB" = "true" ]]; then
            rm -rf grub aphrodite-grub.iso
            if [[ "$target" = "x86" ]]; then
                cp -r ./grub_template ./grub

                cp kernel.flat ./grub/boot/aphrodite.kernel

                sed -i "s@%{VERSION}@$VERSION@g" ./grub/boot/grub/grub.cfg

                grub-mkrescue -o aphrodite-grub.iso grub
                cp aphrodite-grub.iso aphrodite.iso
            fi
        fi
    done

    reset_version_vars
)