#!/bin/bash

function get_version() {
    local TEMP_SUFFIX
    if git add . && git diff --quiet && git diff --cached --quiet 
    then
        echo -n
    else
        TEMP_SUFFIX="-out-of-tree"
    fi
    SUFFIX="$SUFFIX$TEMP_SUFFIX"

    VERSION="${VERSION:-devel-$(git rev-parse --short HEAD)$SUFFIX}"
    if [[ "$VERSION" == "generate" ]]; then
        VERSION="devel-$(git rev-parse --short HEAD)$SUFFIX"
    fi
}

function reset_version_vars() {
    unset TEMP_SUFFIX SUFFIX VERSION
}